// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbqtnkqjvhzhxdmjmqtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicXRua3Fqdmh6aHhkbWptcXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTIxMzAsImV4cCI6MjA2MTYyODEzMH0.ZD5Trt2HL3ZlGvNgNReP8C5IU9c7zQ3O__-gYlnKgdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);